/// Flutter icons CostumIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CostumIcon
///      fonts:
///       - asset: fonts/CostumIcon.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CostumIcon {
  CostumIcon._();

  static const _kFontFam = 'CostumIcon';
  static const _kFontPkg = null;

  static const IconData quoteleft = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quotedblright = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quotedblleft = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData guilsinglright = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData guilsinglleft = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData _notdef = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData endash = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emdash = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData parenright = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData parenleft = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bracketright = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bracketleft = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData braceright = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData seven = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eight = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nine = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData asterisk = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backslash = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bullet = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData colon = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comma = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ellipsis = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exclam = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exclamdown = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData numbersign = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData period = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData periodcentered = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData questiondown = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quotedbl = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quotesingle = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData semicolon = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slash = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData six = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData five = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData four = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData three = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData two = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData one = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zero = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData z = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData y = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData w = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData v = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData u = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData t = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData s = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData r = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData q = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData p = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData o = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData n = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData braceleft = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData T = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData V = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData W = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData X = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Y = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Z = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData a = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData b = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData c = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData d = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData e = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData f = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData g = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData h = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData i = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData j = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData k = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData l = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData m = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData S = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData R = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Q = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData P = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData O = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData N = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData M = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData L = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData K = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData J = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData I = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData H = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData G = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData F = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData E = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData D = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData C = IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData B = IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData A = IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData U = IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bitcoin = IconData(0xf15a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
